### ISSUE TITLE
Build mockup interfaces

### ISSUE THREAD

**Issue by dashohoxha** [EasyGnuPG/ggpg#18]
Build some mockup interfaces using Pencil: https://pencil.evolus.vn/
These should describe the idea that you have about how the application will look and work.
Share and discuss these mockups and get feedback about improving them.

**Comment by dashohoxha** [comment]
Please consider this a priority task.

**Comment by yugeshk** [comment]
![screenshot from 2018-05-25 02-02-06](https://user-images.githubusercontent.com/31157397/40512443-80983df4-5fc0-11e8-81c9-d4f6346fe530.png)

I had something of this sort in mind, as an initial thought.

**Comment by yugeshk** [comment]
There is a lot of empty space at the center - I was thinking of adding a progressbar, but I tried running some tests today - unless the file is really big (of the order of 100s of MB), the time taken is negligible (could probably still do it for show - seems quite pleasing to me personally).

**Comment by yugeshk** [comment]
@sourabhtk37 your opinion?

**Comment by yugeshk** [comment]
> Build some mockup interfaces using Pencil: https://pencil.evolus.vn/

I haven't used a GUI builder for the current prototype (its all direct python code). Can do that for further ones if required.

**Comment by yugeshk** [comment]
> There is a lot of empty space at the center - I was thinking of adding a progressbar, but I tried running some tests today - unless the file is really big (of the order of 100s of MB), the time taken is negligible (could probably still do it for show - seems quite pleasing to me personally).

How about adding a two level step? Something like first Open the file and then Encrypt button. This way if the user happens to select an incorrect file by mistake (say a .sealed file for encryption or a regular file for decryption) we could raise a warning like - "Are you sure you selected the right file?" by writing a check in the logic part.
Let me go ahead and try that too
